"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
truncation_length = 4
truncate_to_repo = false

[package]
disabled = true

[cmd_duration]
min_time = 1_000
show_milliseconds = true
